# Generated by Django 5.0.6 on 2024-05-12 09:13

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField(default='null')),
                ('Roll', models.CharField(max_length=60)),
                ('experience', models.CharField(max_length=60)),
                ('location', models.CharField(default='null', max_length=100)),
                ('ph_number', models.CharField(default='null', max_length=10)),
                ('gmail', models.EmailField(default='null', max_length=254)),
                ('lnkedin', models.CharField(default='null', max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('work_experience', models.TextField(default='null', max_length=500)),
                ('SSLC', models.CharField(max_length=255)),
                ('SSLC_year', models.CharField(max_length=255)),
                ('SSLC_place', models.CharField(default='null', max_length=255)),
                ('SSLC_percentage', models.CharField(default='null', max_length=255)),
                ('HSC', models.CharField(max_length=255)),
                ('HSC_year', models.CharField(max_length=255)),
                ('HSC_place', models.CharField(default='null', max_length=255)),
                ('HSC_percentage', models.CharField(default='null', max_length=255)),
                ('collage_degree_s', models.CharField(default='null', max_length=255)),
                ('collage_degree', models.CharField(max_length=255)),
                ('collage_year', models.CharField(max_length=255)),
                ('collage_place', models.CharField(default='null', max_length=255)),
                ('collage_percentage', models.CharField(default='null', max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('course_year', models.CharField(max_length=255)),
                ('course_place', models.CharField(default='null', max_length=255)),
                ('course_grade', models.CharField(default='null', max_length=255)),
                ('profile_image', models.ImageField(default='null', upload_to=portfolio.models.FileName)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_img', models.ImageField(upload_to=portfolio.models.project_img_FileName)),
                ('project_name', models.CharField(max_length=100)),
                ('project_name_w_p', models.CharField(default='null', max_length=100)),
                ('project_description', models.TextField(max_length=500)),
                ('url_name_project', models.CharField(max_length=30)),
                ('url_name_details', models.CharField(max_length=30)),
                ('language1', models.CharField(default='null', max_length=50)),
                ('language2', models.CharField(default='null', max_length=50)),
                ('language3', models.CharField(default='null', max_length=50)),
                ('language4', models.CharField(default='null', max_length=50)),
                ('language5', models.CharField(default='null', max_length=50)),
                ('language6', models.CharField(default='null', max_length=50)),
                ('language7', models.CharField(default='null', max_length=50)),
                ('language8', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_image', models.ImageField(default='null', upload_to=portfolio.models.skill_img_FileName)),
            ],
        ),
    ]
