# Generated by Django 5.0.6 on 2024-05-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
