# Generated by Django 5.0.6 on 2024-05-13 09:26

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_resume_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='contect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50)),
                ('gmail', models.EmailField(default='null', max_length=254)),
                ('message', models.TextField(default='null', max_length=500)),
                ('message_send_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_photo1',
            field=models.ImageField(default='null', upload_to=portfolio.models.resume_img_FileName),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_photo2',
            field=models.ImageField(default='null', upload_to=portfolio.models.resume_img_FileName),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_photo3',
            field=models.ImageField(default='null', upload_to=portfolio.models.resume_img_FileName),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_photo4',
            field=models.ImageField(default='null', upload_to=portfolio.models.resume_img_FileName),
        ),
    ]
