# Generated by Django 5.0.6 on 2024-05-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_contect_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contect',
            name='message_send_at',
            field=models.DateTimeField(default='null'),
        ),
    ]
