# Generated by Django 5.0.6 on 2024-05-13 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_contect_message_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contect',
            name='message_send_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 15, 39, 36, 945224)),
        ),
    ]
