# Generated by Django 5.0.6 on 2024-05-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_contect_message_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contect',
            name='message_send_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
