# Generated by Django 5.0.6 on 2024-05-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_contect_message_send_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contect',
            name='message',
        ),
    ]
