# Generated by Django 5.0.6 on 2024-05-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_contect_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contect',
        ),
    ]
