# Generated by Django 5.0.6 on 2024-05-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_delete_contect'),
    ]

    operations = [
        migrations.CreateModel(
            name='contect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gmail', models.EmailField(default='null', max_length=254)),
                ('message', models.DateTimeField(default='null')),
                ('message_send_at', models.CharField(default='null', max_length=30)),
            ],
        ),
    ]
