# Generated by Django 5.0.6 on 2024-05-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_contect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contect',
            name='message',
            field=models.TextField(default='null', max_length=500),
        ),
    ]
