# Generated by Django 5.0.6 on 2024-05-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_contect_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contect',
            name='message_send_at',
            field=models.DateTimeField(default='null', max_length=30),
        ),
    ]
