# Generated by Django 5.0.6 on 2024-05-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_contect_message_send_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contect',
            name='message_send_at',
        ),
    ]
